#!/usr/bin/env bash
# =============================================================================
# CargoTrack — Generate Kubernetes Secrets from AWS Secrets Manager
# =============================================================================
# Usage: ./scripts/generate-k8s-secrets.sh
#
# Reads AWS Secrets Manager values (from Terraform-provisioned secrets) and
# generates the k8s/secrets/*.yaml files with properly base64-encoded values.
# These files are gitignored — never commit real secret values.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
INFRA_DIR="${PROJECT_ROOT}/cargotrack-infra/environments/dev"
SECRETS_DIR="${PROJECT_ROOT}/k8s/secrets"
AWS_REGION="${AWS_REGION:-us-east-1}"

RED='\033[0;31m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

info "Reading Terraform outputs..."
cd "${INFRA_DIR}"
DB_SECRET_ARN=$(terraform output -raw db_secret_arn)
APP_SECRET_ARN=$(terraform output -raw application_secret_arn)

info "DB Secret ARN:  ${DB_SECRET_ARN}"
info "App Secret ARN: ${APP_SECRET_ARN}"
echo ""

# ── Read database secret ───────────────────────────────────────────────────
info "Retrieving database credentials from Secrets Manager..."
DB_SECRET=$(aws secretsmanager get-secret-value \
  --secret-id "${DB_SECRET_ARN}" \
  --region "${AWS_REGION}" \
  --query SecretString --output text)

DB_HOST=$(echo "${DB_SECRET}" | jq -r '.host // .endpoint // ""')
DB_PORT=$(echo "${DB_SECRET}" | jq -r '.port // "5432"')
DB_NAME=$(echo "${DB_SECRET}" | jq -r '.dbname // "cargotrack"')
DB_USER=$(echo "${DB_SECRET}" | jq -r '.username // ""')
DB_PASS=$(echo "${DB_SECRET}" | jq -r '.password // ""')

# Strip port from host if endpoint includes it (RDS endpoint format: host:port)
if [[ "${DB_HOST}" == *":"* ]]; then
  DB_PORT_FROM_HOST="${DB_HOST##*:}"
  DB_HOST="${DB_HOST%%:*}"
  if [[ -z "${DB_PORT}" || "${DB_PORT}" == "5432" ]]; then
    DB_PORT="${DB_PORT_FROM_HOST}"
  fi
fi

success "Database credentials retrieved (host: ${DB_HOST}:${DB_PORT})"

# ── Read application secret ────────────────────────────────────────────────
info "Retrieving application secrets from Secrets Manager..."
APP_SECRET=$(aws secretsmanager get-secret-value \
  --secret-id "${APP_SECRET_ARN}" \
  --region "${AWS_REGION}" \
  --query SecretString --output text)

JWT_SECRET=$(echo "${APP_SECRET}" | jq -r '.jwt_secret // ""')
ADMIN_EMAIL=$(echo "${APP_SECRET}" | jq -r '.admin_email // "admin@cargotrack.com"')
ADMIN_PASSWORD=$(echo "${APP_SECRET}" | jq -r '.admin_password // ""')
INTERNAL_API_SECRET=$(echo "${APP_SECRET}" | jq -r '.internal_api_secret // ""')

# Generate INTERNAL_API_SECRET if not present in SM
if [[ -z "${INTERNAL_API_SECRET}" ]]; then
  INTERNAL_API_SECRET=$(openssl rand -hex 32)
  warn "INTERNAL_API_SECRET not in Secrets Manager — generated random value"
fi

success "Application secrets retrieved"
echo ""

# ── Base64 encode all values ───────────────────────────────────────────────
b64() { echo -n "$1" | base64; }

# ── Write db-credentials.yaml ─────────────────────────────────────────────
info "Writing ${SECRETS_DIR}/db-credentials.yaml..."
cat > "${SECRETS_DIR}/db-credentials.yaml" << EOF
# AUTO-GENERATED — DO NOT COMMIT TO VERSION CONTROL
# Generated by scripts/generate-k8s-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: cargotrack
  labels:
    app.kubernetes.io/name: cargotrack
    app.kubernetes.io/component: secrets
type: Opaque
data:
  DATABASE_HOST: $(b64 "${DB_HOST}")
  DATABASE_PORT: $(b64 "${DB_PORT}")
  DATABASE_NAME: $(b64 "${DB_NAME}")
  DATABASE_USER: $(b64 "${DB_USER}")
  DATABASE_PASSWORD: $(b64 "${DB_PASS}")
EOF
success "db-credentials.yaml written"

# ── Write app-secrets.yaml ────────────────────────────────────────────────
info "Writing ${SECRETS_DIR}/app-secrets.yaml..."
cat > "${SECRETS_DIR}/app-secrets.yaml" << EOF
# AUTO-GENERATED — DO NOT COMMIT TO VERSION CONTROL
# Generated by scripts/generate-k8s-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: cargotrack
  labels:
    app.kubernetes.io/name: cargotrack
    app.kubernetes.io/component: secrets
type: Opaque
data:
  JWT_SECRET: $(b64 "${JWT_SECRET}")
  ADMIN_EMAIL: $(b64 "${ADMIN_EMAIL}")
  ADMIN_PASSWORD: $(b64 "${ADMIN_PASSWORD}")
  INTERNAL_API_SECRET: $(b64 "${INTERNAL_API_SECRET}")
EOF
success "app-secrets.yaml written"

echo ""
success "Kubernetes secrets generated. Apply with:"
echo "  kubectl apply -f k8s/secrets/"
echo ""
echo "WARNING: Do not commit the generated secret files to git!"
echo "  Add to .gitignore: k8s/secrets/db-credentials.yaml"
echo "  Add to .gitignore: k8s/secrets/app-secrets.yaml"
