#!/usr/bin/env bash
# post-apply-setup.sh
# Run this AFTER terraform apply completes to wire up Helm values with real AWS resource IDs.
# Usage: bash scripts/post-apply-setup.sh
# Run from: project root (c:\Users\Admin\project\terraform-project\)

set -euo pipefail

INFRA_DIR="cargotrack-v2/cargotrack-infra/environments/dev"
VALUES_FILE="helm/cargotrack/values-dev.yaml"
CLUSTER_NAME="cargotrack"
REGION="us-east-1"

echo "==> Reading terraform outputs..."
cd "$INFRA_DIR"

# Capture all outputs (non-sensitive ones only)
EKS_CLUSTER_NAME=$(terraform output -raw eks_cluster_name)
S3_BUCKET=$(terraform output -raw s3_bucket_name)
EVENT_BUS=$(terraform output -raw event_bus_name)
COMPLIANCE_QUEUE=$(terraform output -raw compliance_queue_url)
AUDIT_TABLE=$(terraform output -raw dynamodb_audit_table)
CORE_ROLE=$(terraform output -raw irsa_core_service_role_arn)
DOCS_ROLE=$(terraform output -raw irsa_document_service_role_arn)
AI_ROLE=$(terraform output -raw irsa_ai_service_role_arn)
ALB_ROLE=$(terraform output -raw irsa_alb_controller_role_arn)
DB_SECRET_ARN=$(terraform output -raw db_secret_arn)
APP_SECRET_ARN=$(terraform output -raw application_secret_arn)
RDS_ENDPOINT=$(terraform output -raw rds_endpoint)

echo "==> Configuring kubectl..."
aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region "$REGION"

echo "==> Verifying cluster nodes..."
kubectl get nodes

echo "==> Retrieving credentials from AWS Secrets Manager..."
DB_SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id "$DB_SECRET_ARN" --region "$REGION" --query "SecretString" --output text)
DB_PASS=$(echo "$DB_SECRET_JSON" | jq -r '.password')

APP_SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id "$APP_SECRET_ARN" --region "$REGION" --query "SecretString" --output text)
JWT_SEC=$(echo "$APP_SECRET_JSON" | jq -r '.jwt_secret')
ADMIN_PASS=$(echo "$APP_SECRET_JSON" | jq -r '.admin_password')

echo "==> Creating Kubernetes Secret for CargoTrack..."
kubectl create namespace cargotrack --dry-run=client -o yaml | kubectl apply -f -
kubectl create secret generic cargotrack-secrets -n cargotrack \
  --from-literal=DATABASE_PASSWORD="$DB_PASS" \
  --from-literal=JWT_SECRET="$JWT_SEC" \
  --from-literal=ADMIN_PASSWORD="$ADMIN_PASS" \
  --dry-run=client -o yaml | kubectl apply -f -

echo "==> Installing AWS Load Balancer Controller..."
helm repo add eks https://aws.github.io/eks-charts --force-update
helm repo update

kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master" 2>/dev/null || true

helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
  -n kube-system \
  --set clusterName="$EKS_CLUSTER_NAME" \
  --set serviceAccount.create=true \
  --set serviceAccount.name=aws-load-balancer-controller \
  --set "serviceAccount.annotations.eks\.amazonaws\.com/role-arn=$ALB_ROLE" \
  --wait --timeout=5m

echo "==> Installing ArgoCD..."
kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
helm repo add argo https://argoproj.github.io/argo-helm --force-update
helm repo update

helm upgrade --install argocd argo/argo-cd \
  -n argocd \
  --set server.service.type=LoadBalancer \
  --wait --timeout=8m

echo "==> ArgoCD admin password:"
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
echo ""

echo "==> ArgoCD server URL:"
kubectl get svc argocd-server -n argocd -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"
echo ""

echo "==> Updating values-dev.yaml with terraform outputs..."
cd -  # back to project root

cat > "$VALUES_FILE" << EOF
# CargoTrack Dev Environment Values
# Auto-generated by post-apply-setup.sh — DO NOT edit manually

global:
  environment: dev
  region: $REGION
  namespace: cargotrack

image:
  pullPolicy: Always

coreService:
  tag: latest
  serviceAccount:
    roleArn: "$CORE_ROLE"

documentService:
  tag: latest
  serviceAccount:
    roleArn: "$DOCS_ROLE"

aiService:
  tag: latest
  serviceAccount:
    roleArn: "$AI_ROLE"
  env:
    MOCK_AGENT: "true"
    TEXTRACT_ENABLED: "false"

frontend:
  tag: latest

aws:
  region: $REGION
  rdsEndpoint: "$RDS_ENDPOINT"
  rdsDatabase: cargotrack
  rdsUsername: cargotrack
  s3BucketName: "$S3_BUCKET"
  eventBusName: "$EVENT_BUS"
  complianceQueueUrl: "$COMPLIANCE_QUEUE"
  auditTableName: "$AUDIT_TABLE"
  dbSecretArn: "$DB_SECRET_ARN"
  appSecretArn: "$APP_SECRET_ARN"
EOF

echo "==> values-dev.yaml updated!"

echo "==> Applying ArgoCD root Application..."
kubectl apply -f gitops/apps/root-app.yaml

echo ""
echo "====== Setup Complete ======"
echo "ArgoCD is watching: helm/cargotrack/"
echo "Push a change to trigger deploy."
echo ""
echo "Monitor ArgoCD sync:"
echo "  kubectl get applications -n argocd -w"
echo ""
echo "Monitor pods:"
echo "  kubectl get pods -n cargotrack -w"
echo ""
echo "Get Ingress ALB DNS (after pods are Running):"
echo "  kubectl get ingress -n cargotrack"
